'''
SCRIPT CRIADO PARA ARMAZENAR AS ABREVIAÇÕES DOS PARÂMETROS DE QUALIDADE DO AR E METEOROLOGIA
'''

VARIAVEIS = [
   'Desvio Padrão Dir. Vento',
   'Precipitação Pluviométrica', 
   'Velocidade do Vento',
   'Velocidade Escalar do Vento',
   'Direção do Vento',
   'Direção Escalar do Vento',
   'Temperatura',
   'Radiação Solar',
   'Radiação Solar Liquida',
   'Umidade Relativa',
   'Pressão Atmosférica',
   'Partículas Totais em Suspensão',
   'Partículas Inaláveis (<2,5µm)',
   'Partículas Inaláveis <2,5µm)',
   'Partículas Inaláveis (<2,5µm',
   'Partículas Inaláveis (<10µm)',
   'Partículas Inaláveis (<10µm',
   'Partículas Inaláveis <10µm)',
   'Monóxido de Nitrogênio',
   'Dióxido de Nitrogênio',
   'Óxidos de Nitrogênio',
   'Ozônio',
   'Dióxido de Enxofre', 
   'Monóxido de Carbono',
   'Hidrocarbonetos Totais',
   'Metano',
   'Hidrocarbonetos Não-Metano',
]

VAR_ALIAS = [
   'Desvio Dir. Vento',
   'Prec.',
   'Vel. Vento',
   'Vel. Vento',
   'Dir. Vento',
   'Dir. Vento',
   'Temp',
   'Rad. Solar',
   'Rad. Solar Liq.',
   'UR',
   'Pressão',
   'PTS',
   'MP2,5',
   'MP2,5',
   'MP2,5',
   'MP10',
   'MP10',
   'MP10',
   'NO',
   'NO2',
   'NOX',
   'O3',
   'SO2',
   'CO',
   'HCT',
   'CH4',
   'HCTnM'
]

ALIAS_OPENAIR = [
   'sdwd',
   'rf',
   'ws',
   'ws',
   'wd',
   'wd',
   't',
   'sr',
   'lsr',
   'p',
   'pts',
   'pm25',
   'pm25',
   'pm25',
   'pm10',
   'pm10',
   'pm10',
   'no',
   'no2',
   'nox',
   'o3',
   'so2',
   'co',
   'hct',
   'ch4',
   'hctnm'
]