'''
SCRIPT CRIADO PARA ARMAZENAR AS ABREVIAÇÕES DOS PARÂMETROS DE QUALIDADE DO AR E METEOROLOGIA
'''

ARIAVEIS = [
   'Precipitação Pluviométrica', 
   'Velocidade do Vento',
   'Direção do Vento',
   'Temperatura',
   'Radiação Solar',
   'Umidade Relativa',
   'Pressão Atmosférica',
   'Partículas Totais em Suspensão',
   'Partículas Inaláveis (<2,5µm)',
   'Partículas Inaláveis <2,5µm)',
   'Partículas Inaláveis (<2,5µm',
   'Partículas Inaláveis (<10µm)',
   'Partículas Inaláveis (<10µm',
   'Partículas Inaláveis <10µm)',
   'Monóxido de Nitrogênio',
   'Dióxido de Nitrogênio',
   'Óxidos de Nitrogênio',
   'Ozônio',
   'Dióxido de Enxofre', 
   'Monóxido de Carbono',
   'Hidrocarbonetos Totais',
   'Metano',
   'Hidrocarbonetos Não-Metano',
]

VAR_ALIAS = [
   'Prec.',
   'Vel. Vento',
   'Dir. Vento',
   'Temp',
   'Rad. Solar',
   'UR',
   'Pressão',
   'PTS',
   'MP2,5',
   'MP2,5',
   'MP2,5',
   'MP10',
   'MP10',
   'MP10',
   'NO',
   'NO2',
   'NOX',
   'O3',
   'SO2',
   'CO',
   'HCT',
   'CH4',
   'HCTnM'
]